apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: magda-minion-ckan-publisher
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  template:
    metadata:
      labels:
        service: magda-minion-ckan-publisher
    spec:
      containers:
      - name: magda-minion-ckan-publisher
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: NODE_PORT
          value: "80"
        - name: REGISTRY_URL
          value: "http://registry-api/v0"
        - name: ENABLE_MULTI_TENANTS
{{- if .Values.global.enableMultiTenants }}
          value: "true"
{{- else }}
          value: "false"
{{- end }}
        - name: TENANT_URL
          value: "http://tenant-api/v0"
        - name: USER_ID
          value: {{ .Values.global.defaultAdminUserId }}
        - name: INTERNAL_URL
          value: "http://magda-minion-ckan-publisher"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        - name: CKAN_SERVER_URL
          value: {{ .Values.ckanServerUrl }}
        - name: CKAN_DEFAULT_API_KEY
          value: {{ .Values.ckanDefaultAPIKey }}
        - name: EXTERNAL_URL
          value: {{ .Values.global.externalUrl }}
