apiVersion: apps/v1
kind: Deployment
metadata:
  name: magda-minion-ckan-exporter
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      service: magda-minion-ckan-exporter
  template:
    metadata:
      labels:
        service: magda-minion-ckan-exporter
    spec:
      {{- include "magda.imagePullSecrets" . | indent 6 }}
      volumes:
      - name: ckan-server-api-key-map
        secret:
          secretName: ckan-exporter-secrets
      containers:
      - name: magda-minion-ckan-exporter
        image: {{ include "magda.image" . | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" . | quote }}
        volumeMounts:
        - name: ckan-server-api-key-map
          mountPath: "/etc/config"
          readOnly: true
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: NODE_PORT
          value: "80"
        - name: REGISTRY_URL
          value: "http://registry-api/v0"
        - name: ENABLE_MULTI_TENANTS
{{- if .Values.global.enableMultiTenants }}
          value: "true"
{{- else }}
          value: "false"
{{- end }}
        - name: TENANT_URL
          value: "http://tenant-api/v0"
        - name: USER_ID
          value: {{ .Values.global.defaultAdminUserId }}
        - name: INTERNAL_URL
          value: "http://magda-minion-ckan-exporter"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        - name: CKAN_SERVER_URL
          value: {{ .Values.ckanServerUrl }}
        - name: USER_ID
          value: {{ .Values.global.defaultAdminUserId | default .Values.defaultAdminUserId }}
        - name: EXTERNAL_URL
          value: {{ .Values.global.externalUrl }}
        - name: CKAN_SERVER_KEY_MAP
          value: /etc/config/ckan_server_api_key_map.json
