apiVersion: v2
name: magda-minion-ckan-exporter
description: A Helm chart for Magda CKAN Exporter Minion
version: "2.0.0-alpha.0"
kubeVersion: ">= 1.14.0-0"
home: "https://github.com/magda-io/magda-minion-ckan-exporter"
sources: [ "https://github.com/magda-io/magda-minion-ckan-exporter" ]
annotations:
  magdaModuleType: "minion"
dependencies:
  - name: magda-common
    version: "2.1.1"
    repository: "oci://ghcr.io/magda-io/charts"
