image:
  name: "magda-minion-ckan-exporter"
  # repository:
  # pullPolicy:
  # imagePullSecret:

global:
  image: {}
  rollingUpdate:
    maxUnavailable: 0
  minions:
    image: {}

resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 100m

defaultImage:
  repository: ghcr.io/magda-io
  pullPolicy: IfNotPresent
  imagePullSecret: false

defaultAdminUserId: "00000000-0000-4000-8000-000000000000"
